# Generated by Django 5.2.15 on 2026-08-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_salarystructure_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='unpaid_leave_days',
            field=models.IntegerField(default=0),
        ),
    ]
