# Generated by Django 6.0.8 on 2026-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0006_payrollrun_is_locked_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('pf_percentage', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('esi_percentage', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('pf_wage_ceiling', models.DecimalField(decimal_places=2, default=21000.0, max_digits=10)),
                ('casual_leave_days', models.IntegerField(default=12)),
                ('sick_leave_days', models.IntegerField(default=12)),
                ('earned_leave_days', models.IntegerField(default=15)),
            ],
        ),
    ]
