# Generated by Django 6.0.8 on 2026-08-06 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrearsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('old_basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrears_records', to='payroll_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FullFinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_day', models.DateField()),
                ('pending_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='payroll_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('FINANCE', 'Finance'), ('PAYROLL_EXECUTIVE', 'Payroll Executive'), ('REPORTING_MANAGER', 'Reporting Manager'), ('EMPLOYEE', 'Employee')], max_length=20)),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='payroll_app.employee')),
            ],
        ),
    ]
