# Generated by Django 5.2.15 on 2026-08-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0012_remove_employee_user_alter_arrearsrecord_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_letter_signed', models.BooleanField(default=False)),
                ('documents_collected', models.BooleanField(default=False)),
                ('bank_details_verified', models.BooleanField(default=False)),
                ('it_equipment_assigned', models.BooleanField(default=False)),
                ('orientation_scheduled', models.BooleanField(default=False)),
                ('is_offboarding', models.BooleanField(default=False, help_text='Check if this is an offboarding checklist instead of onboarding')),
                ('exit_interview_done', models.BooleanField(default=False)),
                ('assets_returned', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='payroll_app.employee')),
            ],
        ),
    ]
