# Generated by Django 5.2.15 on 2026-08-21 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0013_onboardingchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=10)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Basic')], default='FIXED', max_length=12)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_employer_contribution', models.BooleanField(default=False)),
                ('include_in_ctc', models.BooleanField(default=True)),
                ('show_in_payslip', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalaryComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Fixed amount, or percentage if component is percentage-based', max_digits=10)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='payroll_app.employee')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.salarycomponent')),
            ],
            options={
                'ordering': ['-effective_from'],
                'unique_together': {('employee', 'component', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='SalaryTemplateComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Fixed amount, or percentage if component is percentage-based', max_digits=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.salarycomponent')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll_app.salarytemplate')),
            ],
            options={
                'unique_together': {('template', 'component')},
            },
        ),
    ]
