# Generated by Django 5.2.15 on 2026-08-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0019_userregistrationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
