# Generated by Django 5.2.15 on 2026-08-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0021_leaverequest_approved_at_leaverequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
