# Generated by Django 5.2.15 on 2026-09-03 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0026_clientcomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('BIOMETRIC', 'Biometric')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BiometricPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20)),
                ('punch_time', models.DateTimeField()),
                ('punch_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('raw_payload', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_punches', to='payroll_app.employee')),
            ],
            options={
                'ordering': ['-punch_time'],
            },
        ),
    ]
